### ISSUE TITLE
Error with mongoid 6.0.3

### ISSUE THREAD

**Issue by forumd** [ElMassimo/mongoid_includes#10] opened 2017-01-10 09:15 UTC
Hi,
Mongoid 6.0.3 raise an error with mongoid_includes:
```
There was an exception - NoMethodError(undefined method `first' for false:FalseClass)
/opt/rvm/gems/ruby-2.3.3/gems/mongoid-6.0.3/lib/mongoid/contextual/mongo.rb:271:in `find_first'
/opt/rvm/gems/ruby-2.3.3/gems/mongoid-6.0.3/lib/mongoid/contextual.rb:20:in `find_first'
/opt/rvm/gems/ruby-2.3.3/gems/mongoid-6.0.3/lib/mongoid/findable.rb:114:in `find_by'
/Projects/sofred2016/app/channels/application_cable/connection.rb:12:in `find_verified_user'
/Projects/sofred2016/app/channels/application_cable/connection.rb:6:in `connect'
/opt/rvm/gems/ruby-2.3.3/gems/actioncable-5.0.1/lib/action_cable/connection/base.rb:167:in `handle_open'
/opt/rvm/gems/ruby-2.3.3/gems/actioncable-5.0.1/lib/action_cable/server/worker.rb:58:in `block in invoke'
/opt/rvm/gems/ruby-2.3.3/gems/actioncable-5.0.1/lib/action_cable/server/worker.rb:39:in `block in work'
/opt/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:126:in `call'
/opt/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/opt/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/opt/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/opt/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/opt/rvm/gems/ruby-2.3.3/gems/actioncable-5.0.1/lib/action_cable/engine.rb:60:in `block (4 levels) in <class:Engine>'
/opt/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/opt/rvm/gems/ruby-2.3.3/gems/actioncable-5.0.1/lib/action_cable/engine.rb:55:in `block (3 levels) in <class:Engine>'
/opt/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
/opt/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/opt/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
/opt/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:447:in `block in around'
/opt/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/opt/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/opt/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:750:in `_run_work_callbacks'
/opt/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/opt/rvm/gems/ruby-2.3.3/gems/actioncable-5.0.1/lib/action_cable/server/worker.rb:38:in `work'
/opt/rvm/gems/ruby-2.3.3/gems/actioncable-5.0.1/lib/action_cable/server/worker.rb:56:in `invoke'
/opt/rvm/gems/ruby-2.3.3/gems/actioncable-5.0.1/lib/action_cable/server/worker.rb:51:in `block in async_invoke'
/opt/rvm/gems/ruby-2.3.3/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/opt/rvm/gems/ruby-2.3.3/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/opt/rvm/gems/ruby-2.3.3/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/opt/rvm/gems/ruby-2.3.3/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/opt/rvm/gems/ruby-2.3.3/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/opt/rvm/gems/ruby-2.3.3/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by forumd** [comment] 2017-01-10 09:16
https://jira.mongodb.org/browse/MONGOID-4370

**Comment by ElMassimo** [comment] 2017-01-10 16:12
Thanks for the report, closing as a duplicate of #9, happy to accept any patch for the breaking changes in `6.0.1`, but currently not able to take a look into it 😃

**Closed by ElMassimo** 2017-01-10 16:12 UTC

**Comment by ElMassimo** [comment] 2017-01-10 17:01
@forumd [__v2.0.0__](https://rubygems.org/gems/mongoid_includes/versions/2.0.0) is now available, thanks again for the bug report!
